japp/config/routes.rb
Rails.application.routes.draw do
  get 'fwelcome/index'
  devise_for :userts
  get 'user/index'
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

japp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

japp/app/models/usert.rb
class Usert < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

japp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_params, if: :devise_controller?
  def configure_devise_params
    devise_parameter_sanitizer.permit(:sign_up) do |usert|
      usert.permit(:name, :email, :password, :password_confirmation)
    end
    end
end

japp/app/controllers/fwelcome_controller.rb
class FwelcomeController < ApplicationController
  def index
  end
end

japp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

japp/app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

japp/app/helpers/application_helper.rb
module ApplicationHelper
end

japp/app/helpers/fwelcome_helper.rb
module FwelcomeHelper
end

japp/app/helpers/home_helper.rb
module HomeHelper
end

japp/app/helpers/user_helper.rb
module UserHelper
end

japp/app/views/fwelcome/index.html.erb
<% if usert_signed_in? %>
  <h2>Bienvenid@ <%= current_usert.name%></h2>
  <% WelcomeMailer.notify(current_usert.email).deliver_now %>
  <% else %>
  <h2>Do you want to be part of our community</h2>
<% end %>

japp/app/views/home/index.html.erb
<% if usert_signed_in? %>
  <h2>Bienvenid@ <%= current_usert.name%></h2>
  <p><%= link_to 'Deseas Recibir Contenido Exclusivo en tu correo?', controller: 'fwelcome' %></p>
  <% else %>
  <h2>Do you want to be part of our community</h2>
<% end %>

japp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Japp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>ProyectArt</h1>
    <p>Smile Works</p>
    <ul class="nav justify-content-end">
      <% if usert_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Salir', destroy_usert_session_path, method: :delete %>
      </li>

      <% else %>
      <li class="nav-item">
        <%= link_to 'Ingresar', new_usert_session_path  %>
      </li>
      <li class="nav-item">
        <%= link_to 'Registrarme', new_usert_registration_path %>
      </li>
      <% end %>
    </ul>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

japp/app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>